FROM --platform=linux/amd64 nvidia/cuda:12.1.1-devel-ubuntu22.04
ADD requirements.txt /requirements.txt

# fix tzdata
ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install software-properties-common -y && apt update
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt update && apt install python3.13-full python3.13-distutils python3-pip htop curl vim libpq-dev libprotobuf-dev protobuf-compiler cmake build-essential pkg-config -y
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.13 1 && update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1

RUN python3.13 -m pip install --upgrade pip
# https://github.com/yaml/pyyaml/issues/724
RUN python3.13 -m pip install --no-build-isolation pyyaml==6.0.2
RUN python3.13 -m pip install flash-attn --no-build-isolation
RUN python3.13 -m pip install -r /requirements.txt

RUN date -u > /docker-build-time.txt
RUN echo "builder: GitHub Actions" >> /docker-build.txt
RUN echo "base: nvidia/cuda:12.1.1-devel-ubuntu22.04" >> /docker-build.txt
